config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  match '/music',   to: 'static#music',   via: 'get'
  match '/lyrics',  to: 'static#lyrics',  via: 'get'
  match '/shows',   to: 'static#shows',   via: 'get'
  match '/contact', to: 'static#contact', via: 'get'
  match '/about',   to: 'static#about',   via: 'get'
  post 'send' =>        'static#sendit'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    
  end

  def music
    
  end

  def lyrics
    
  end

  def shows
    
  end

  def contact
    
  end

  def about
    
  end

  def sendit
    if Contact.email(params).deliver
      flash[:success] = "Thank you!  Your message has been sent!"
    else
      flash[:error] = "Oops!  Something went wrong"
    end
      redirect_to contact_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contact/email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <style>
    i {
      color: #cccccc;
    }
  </style>
</head>
<body>
  <h4><%= @params[:name] %> <i><%= "<#{@params[:email]}>" %></i> contacted you,</h4>
  <p><%= @params[:body] %></p>
</body>
</html>

app/views/contact/email.text.erb
<%= @params[:name] %> <%= "<#{@params[:email]}>" %> contacted you,
<%= @params[:body] %>

app/views/layouts/_header.html.haml
.container-fluid
  %a{ href: '/' }
    = image_tag('banner.svg', class: "img-responsive center-block")
.container-fluid.navigation
  .container
    .row
      .col-md-2
        %h1.no-margin.text-center.white 
          = link_to "Home", root_path, class: "nav-link"
      .col-md-2
        %h1.no-margin.text-center.white 
          = link_to "Music", music_path, class: "nav-link"
      .col-md-2
        %h1.no-margin.text-center.white
          = link_to "Lyrics", lyrics_path, class: "nav-link"
      .col-md-2
        %h1.no-margin.text-center.white 
          = link_to "Shows", shows_path, class: "nav-link"
      .col-md-2
        %h1.no-margin.text-center.white 
          = link_to "Contact", contact_path, class: "nav-link"
      .col-md-2
        %h1.no-margin.text-center.white 
          = link_to "About", about_path, class: "nav-link"
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title A Four Word Story
    %meta{ charset: 'utf-8' }
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }
    %meta{ name: 'viewport', content: 'width=device-width', 'initial-scale' => '1.0' }
    %meta{ name: 'description', content: 'A Four Word Story' }
    %meta{ name: 'author', content: 'A Four Word Story' }
    %link{ rel: 'stylesheet', href: 'http://fonts.googleapis.com/css?family=Roboto:100,300|Amatic+SC' }
    %link{ rel: 'stylesheet', href: '//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' }
    %link{ rel: 'stylesheet', href: '//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' }
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    %script{ src: '//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' }
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      .row.flash
        .col-md-8.col-md-offset-2.big-top
          - flash.each do |key, value|
            .alert.alert-dismissable
              %button.close{ type: 'button', data: { dismiss: 'alert' } } 
                %i.fa.fa-times-circle
              %h2.no-margin
                = value
      .row
        = yield